/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qlysinhvien;

import javax.swing.JOptionPane;

/**
 *
 * @author tduy2
 */
public class JF_Login extends javax.swing.JFrame {

    /**
     * Creates new form JF_Login
     */
    QuanLyTaiKhoan qlTK = new QuanLyTaiKhoan();

    public JF_Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtTaiKhoan = new javax.swing.JTextField();
        btnDangNhap = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        txtMatKhau = new javax.swing.JPasswordField();
        radAdmin = new javax.swing.JRadioButton();
        radSinhVien = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Tài khoản");

        jLabel2.setText("Mật khẩu");

        btnDangNhap.setBackground(java.awt.SystemColor.textHighlight);
        btnDangNhap.setText("Đăng nhập");
        btnDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangNhapActionPerformed(evt);
            }
        });

        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        txtMatKhau.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtMatKhauKeyPressed(evt);
            }
        });

        buttonGroup1.add(radAdmin);
        radAdmin.setText("Admin");

        buttonGroup1.add(radSinhVien);
        radSinhVien.setText("SinhVien");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(38, 38, 38))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radAdmin)
                            .addComponent(jLabel1))
                        .addGap(20, 20, 20)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtTaiKhoan, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
                    .addComponent(txtMatKhau))
                .addContainerGap(123, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(btnDangNhap)
                .addGap(82, 82, 82)
                .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(radSinhVien)
                .addGap(89, 89, 89))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radAdmin)
                    .addComponent(radSinhVien))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(txtTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDangNhap)
                    .addComponent(btnThoat))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangNhapActionPerformed
        String quyen = "";
        for (TaiKhoan tk : qlTK.listTK) {
            quyen = tk.getQuyen();
        }
        if (radSinhVien.isSelected() == true) {
            if (qlTK.DangNhap(txtTaiKhoan.getText(), txtMatKhau.getText()) == true) {
                if (quyen.equals("SinhVien")) {
                    dispose();
                    String maSV = qlTK.layMaSVDangNhap(txtTaiKhoan.getText());
                    JF_SinhVien jfsv = new JF_SinhVien(maSV);
                    jfsv.setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(this, "Kiểm tra lại quyền đăng nhập !!");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Sai tài khoản hoặc mật khẩu");
            }
        } else if (radAdmin.isSelected() == true) {
            if (qlTK.DangNhap(txtTaiKhoan.getText(), txtMatKhau.getText())) {
                if (quyen.equals("Admin")) {
                    dispose();
                    JF_Admin jfad = new JF_Admin();
                    jfad.setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(this, "Kiểm tra lại quyền đăng nhập !!");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Sai tài khoản hoặc mật khẩu");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Bạn phải chọn quyền đăng nhập");
        }

    }//GEN-LAST:event_btnDangNhapActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnThoatActionPerformed

    private void txtMatKhauKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMatKhauKeyPressed
//        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
//            if (radAdmin.isSelected() == true) {
//                File f = new File("Admin.txt");
//                try {
//                    FileReader fr = new FileReader(f);
//                    BufferedReader br = new BufferedReader(fr);
//                    String line = "";
//                    String[] arr;
//                    Boolean ketQua = false;
//                    while ((line = br.readLine()) != null) {
//                        arr = line.split("-");
//                        if (arr[0].equals(txtTaiKhoan.getText()) && arr[1].equals(txtMatKhau.getText())) {
//                            ketQua = true;
//                            break;
//                        }
//                    }
//                    if (ketQua == true) {
//                        JOptionPane.showMessageDialog(this, "Đăng Nhập Thành Công !!");
//                        JF_Admin jfad = new JF_Admin();
//                        jfad.show();
//                        //this.dispose();
//                        this.hide();
//                    } else {
//                        JOptionPane.showMessageDialog(this, "Sai tài khoản hoặc mật khẩu !!");
//                    }
//                } catch (FileNotFoundException ex) {
//                    Logger.getLogger(JF_Login.class.getName()).log(Level.SEVERE, null, ex);
//                } catch (IOException ex) {
//                    Logger.getLogger(JF_Login.class.getName()).log(Level.SEVERE, null, ex);
//                }
//            } else if (radSinhVien.isSelected() == true) {
//                boolean flag = false;
//                for (TaiKhoanSV tK : listTK.list) {
//                    if (tK.isTrangThai() == true || tK.isTrangThai() == false) {
//                        tK.setTrangThai(false);
//                        listTK.ghiFileTaiKhoanSV("TKSinhVien.txt");
//                    }
//                }
//                for (TaiKhoanSV tK : listTK.list) {
//                    if (tK.getMatKhau().equals(txtMatKhau.getText()) && tK.getTaiKhoan().equals(txtTaiKhoan.getText())) {
//                        //if (tK.isTrangThai() != true) {
//                            flag = true;
//                            tK.setTrangThai(true);
//                            listTK.ghiFileTaiKhoanSV("TKSinhVien.txt");
//                            JF_SinhVien jf = new JF_SinhVien();
//                            jf.show();
//                            this.dispose();
//                        }
//                        // listTK.list.clear();
//                    }
//                    if (flag == false) {
//                        JOptionPane.showMessageDialog(null, "Tài khoản hoặc mật khẩu không đúng");
//                    }
//                } else {
//                    JOptionPane.showMessageDialog(this, "Bạn phải Chọn Quyền Đăng Nhập");
//                }
//            }
    }//GEN-LAST:event_txtMatKhauKeyPressed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JF_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JF_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JF_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JF_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JF_Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangNhap;
    private javax.swing.JButton btnThoat;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton radAdmin;
    private javax.swing.JRadioButton radSinhVien;
    private javax.swing.JPasswordField txtMatKhau;
    private javax.swing.JTextField txtTaiKhoan;
    // End of variables declaration//GEN-END:variables
}
