/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qlysinhvien;

import qlysinhvien.JF_Admin;
import qlysinhvien.Khoa;
import qlysinhvien.SinhVien;
import com.sun.corba.se.impl.protocol.giopmsgheaders.Message;
import java.awt.Dialog;
import java.awt.event.WindowEvent;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.naming.AuthenticationException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import qlysinhvien.QLySinhVien;
import qlysinhvien.QlyKhoa;

/**
 *
 * @author Administrator
 */
public class JF_QuanLySinhvien extends javax.swing.JFrame {

    /**
     * Creates new form JF_Sinhvien
     */
    QLySinhVien qlySinhVien = new QLySinhVien();
    QlyKhoa qlyKhoa = new QlyKhoa();
//    QLyTaiKhoanSV qlTaiKhoanSV = new QLyTaiKhoanSV();
    SimpleDateFormat spdf = new SimpleDateFormat("yyyy-MM-dd");

    public JF_QuanLySinhvien() {
        qlyKhoa.hienThiList();
        initComponents();
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtMaSV = new javax.swing.JTextField();
        txtHoTen = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_info = new javax.swing.JTable();
        btn_them = new javax.swing.JButton();
        btn_sua = new javax.swing.JButton();
        btn_xoa = new javax.swing.JButton();
        btn_thoat = new javax.swing.JButton();
        btnHienThi = new javax.swing.JButton();
        btnTimSV = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtNoiSinh = new javax.swing.JTextField();
        txtQuan = new javax.swing.JTextField();
        labelQuan = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtHocBong = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        rbtnNam = new javax.swing.JRadioButton();
        rbtnNu = new javax.swing.JRadioButton();
        cboTenKhoa = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        txtDiaChi = new javax.swing.JTextField();
        btnSapXep = new javax.swing.JButton();
        ngaySinh = new com.toedter.calendar.JDateChooser();

        jLabel2.setText("jLabel2");

        jLabel5.setText("jLabel5");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("QUẢN LÝ SINH VIÊN");

        jLabel3.setText("Mã sinh viên");

        jLabel4.setText("Họ tên");

        jLabel6.setText("Ngày sinh");

        table_info.setAutoCreateRowSorter(true);
        table_info.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        table_info.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã sinh viên", "Họ tên", "Giới tính", "Ngày sinh", "Nơi sinh", "Địa chỉ", "Quận", "Mã khoa", "Học bổng"
            }
        ));
        table_info.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        table_info.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_infoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table_info);

        btn_them.setBackground(java.awt.SystemColor.textHighlight);
        btn_them.setForeground(new java.awt.Color(255, 255, 255));
        btn_them.setText("Thêm");
        btn_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themActionPerformed(evt);
            }
        });

        btn_sua.setBackground(java.awt.SystemColor.textHighlight);
        btn_sua.setForeground(new java.awt.Color(255, 255, 255));
        btn_sua.setText("Sửa");
        btn_sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_suaActionPerformed(evt);
            }
        });

        btn_xoa.setBackground(java.awt.SystemColor.textHighlight);
        btn_xoa.setForeground(new java.awt.Color(255, 255, 255));
        btn_xoa.setText("Xoá");
        btn_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaActionPerformed(evt);
            }
        });

        btn_thoat.setBackground(java.awt.SystemColor.textHighlight);
        btn_thoat.setForeground(new java.awt.Color(255, 255, 255));
        btn_thoat.setText("Thoát");
        btn_thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_thoatActionPerformed(evt);
            }
        });

        btnHienThi.setBackground(java.awt.SystemColor.textHighlight);
        btnHienThi.setForeground(new java.awt.Color(255, 255, 255));
        btnHienThi.setText("Hiển thị");
        btnHienThi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHienThiActionPerformed(evt);
            }
        });

        btnTimSV.setBackground(java.awt.SystemColor.textHighlight);
        btnTimSV.setForeground(new java.awt.Color(255, 255, 255));
        btnTimSV.setText("Tìm sinh viên");
        btnTimSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimSVActionPerformed(evt);
            }
        });

        jLabel7.setText("Nơi sinh");

        labelQuan.setText("Quận");

        jLabel8.setText("Tên khoa");

        jLabel9.setText("Học bổng");

        jLabel10.setText("Giới tính");

        buttonGroup1.add(rbtnNam);
        rbtnNam.setText("Nam");

        buttonGroup1.add(rbtnNu);
        rbtnNu.setText("Nữ");

        jLabel11.setText("Địa chỉ");

        btnSapXep.setBackground(java.awt.SystemColor.textHighlight);
        btnSapXep.setForeground(new java.awt.Color(255, 255, 255));
        btnSapXep.setText("Sắp xếp");
        btnSapXep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSapXepActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnTimSV)
                        .addGap(26, 26, 26)
                        .addComponent(btn_them, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(btn_sua, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(419, 419, 419)
                                .addComponent(btn_thoat, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 86, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 791, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rbtnNam)
                                        .addGap(97, 97, 97)
                                        .addComponent(rbtnNu))
                                    .addComponent(txtHoTen, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                                    .addComponent(txtMaSV, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                                    .addComponent(txtNoiSinh, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                                    .addComponent(ngaySinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(108, 108, 108)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(cboTenKhoa, 0, 298, Short.MAX_VALUE)
                                            .addComponent(txtHocBong)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(labelQuan, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel11))
                                        .addGap(27, 27, 27)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtQuan, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                                            .addComponent(txtDiaChi)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btn_xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(46, 46, 46)
                                        .addComponent(btnHienThi)
                                        .addGap(49, 49, 49)
                                        .addComponent(btnSapXep)))))
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(422, 422, 422)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMaSV, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(66, 66, 66)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rbtnNam)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbtnNu)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ngaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNoiSinh, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtQuan, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelQuan, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cboTenKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtHocBong)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnTimSV)
                            .addComponent(btn_them)
                            .addComponent(btn_sua)
                            .addComponent(btn_xoa)
                            .addComponent(btnHienThi)
                            .addComponent(btnSapXep))))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_thoat, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themActionPerformed
        DefaultTableModel model = (DefaultTableModel) table_info.getModel();
        Boolean ketQua = true;
        String gioiTinh = "";
        String maKhoa = qlyKhoa.layMaKhoa(cboTenKhoa.getSelectedItem().toString());
        if (rbtnNam.isSelected() == true) {
            gioiTinh = "Nam";
        } else {
            gioiTinh = "Nữ";
        }
        try {
            SinhVien sv = new SinhVien(txtMaSV.getText(), txtHoTen.getText(), gioiTinh,  spdf.format(ngaySinh.getDate() ), txtNoiSinh.getText(), txtDiaChi.getText(),   txtQuan.getText(), maKhoa , Integer.parseInt(txtHocBong.getText()));
            for (int i = 0; i < model.getRowCount(); i++) {
                if (model.getValueAt(i, 1).equals(txtMaSV.getText())) {
                    ketQua = false;
                    break;
                }
            }
            if (ketQua == false) {
                JOptionPane.showMessageDialog(this, "Trùng Mã Sinh Viên");
            } else {
                qlySinhVien.themSinhVien(sv);
                hienThi();
            }
        } catch (IllegalArgumentException ex) {
            JOptionPane.showMessageDialog(this, ex);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex);
        }
    }//GEN-LAST:event_btn_themActionPerformed

    private void btn_suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_suaActionPerformed
        DefaultTableModel tblModel = (DefaultTableModel) table_info.getModel();
        int d = table_info.getSelectedRow();
        String gioiTinh = "";
        if (rbtnNam.isSelected() == true) {
            gioiTinh = "Nam";
        } else {
            gioiTinh = "Nu";
        }
        String maKhoa = "";
        try {
            if (btn_sua.getText().equals("Sửa")) {
                btn_sua.setText("Chế Độ Sửa");
                txtMaSV.setEnabled(false);
                cboTenKhoa.setEnabled(false);
                btn_them.setEnabled(false);
                btn_xoa.setEnabled(false);
            } else {
                SinhVien sv = new SinhVien(txtMaSV.getText(), txtHoTen.getText(), gioiTinh, spdf.format(ngaySinh.getDate()), txtNoiSinh.getText(), txtDiaChi.getText(), txtQuan.getText(),   qlyKhoa.layMaKhoa(cboTenKhoa.getSelectedItem().toString()), Integer.parseInt(txtHocBong.getText()));
                int j = JOptionPane.showConfirmDialog(this, "Do you want edition ? ", "Confirm",
                        JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                if (j == JOptionPane.YES_OPTION) {
                    if (table_info.getSelectedRowCount() > 0) {
                        JOptionPane.showMessageDialog(null,  qlyKhoa.layMaKhoa(cboTenKhoa.getSelectedItem().toString()));
                        qlySinhVien.suaSinhVien(sv);
                        hienThi();
                    } else {
                        JOptionPane.showMessageDialog(this, "Hãy chọn một bảng !!");
                    }
                    btn_sua.setText("Sửa");
                    txtMaSV.setEnabled(true);
                    btn_them.setEnabled(true);
                    btn_xoa.setEnabled(true);
                    cboTenKhoa.setEnabled(true);
                }
            }
        } catch (Exception ex) {
            Logger.getLogger(JF_QuanLySinhvien.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_suaActionPerformed
    public void hienThi() {
        DefaultTableModel modelTable = (DefaultTableModel) table_info.getModel();
        modelTable.setRowCount(0);
        qlySinhVien.hienThiList();
        try {
            //SinhVien sv1 = new SinhVien(txt_maSV.getText(),txt_hoTen.getText(),txt_Lop.getText());
            String[] array = new String[]{};
            for (SinhVien sv : qlySinhVien.list) {
                array = new String[]{sv.getMaSV(), sv.getHoTen(), sv.getGioiTinh(), sv.getNgaySinh(), sv.getNoiSinh(), sv.getDiaChi(), sv.getQuan(), sv.getMaKhoa(), String.valueOf(sv.getHocBong())};
                modelTable.addRow(array);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "" + ex);
        }

    }
    private void table_infoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_infoMouseClicked

        int dong = table_info.getSelectedRow();
        String[] arr = new String[]{
            table_info.getValueAt(dong, 0).toString(), table_info.getValueAt(dong, 1).toString(), table_info.getValueAt(dong, 2).toString(), table_info.getValueAt(dong, 3).toString(),
            table_info.getValueAt(dong, 4).toString(), table_info.getValueAt(dong, 5).toString(), table_info.getValueAt(dong, 6).toString(), table_info.getValueAt(dong, 7).toString(),
            table_info.getValueAt(dong, 8).toString()
        };
        if (table_info.getValueAt(dong, 2).equals("Nam")) {
            rbtnNam.setSelected(true);
        } else {
            rbtnNu.setSelected(true);
        }
        cboTenKhoa.getModel().setSelectedItem(qlyKhoa.layTenKhoa(arr[7]));
        txtMaSV.setText(arr[0]);
        txtHoTen.setText(arr[1]);
        ngaySinh.setDateFormatString(arr[3]);
        txtNoiSinh.setText(arr[4]);
        txtDiaChi.setText(arr[5]);
        txtQuan.setText(arr[6]);
        txtHocBong.setText(arr[8]);
    }//GEN-LAST:event_table_infoMouseClicked

    private void btn_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaActionPerformed

        DefaultTableModel dtmodel = (DefaultTableModel) table_info.getModel();
        if (btn_xoa.getText() == "Xóa") {
            txtMaSV.setEnabled(false);
            btn_xoa.setText("Hủy Chế Độ Xóa");
        } else {
            if (table_info.getSelectedRowCount() > 0) {
                SinhVien sv;
                try {
                    int r = JOptionPane.showConfirmDialog(this, "Bạn có muốn xóa không ? ", "Hộp Thoại", JOptionPane.YES_NO_OPTION);
                    if (r == JOptionPane.YES_OPTION) {
                        sv = new SinhVien();
                        sv.setMaSV(txtMaSV.getText());
                        qlySinhVien.xoaSinhVien(sv);
                    }
                } catch (Exception ex) {
                    Logger.getLogger(JF_QuanLyKhoa.class.getName()).log(Level.SEVERE, null, ex);
                }
                txtMaSV.setEnabled(true);
                btn_xoa.setText("Xóa");
            } else {
                JOptionPane.showMessageDialog(this, "Hãy chọn một bảng !");
            }
        }
    }//GEN-LAST:event_btn_xoaActionPerformed

    private void btnHienThiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHienThiActionPerformed
        // TODO add your handling code here:
        DefaultTableModel modelTable = (DefaultTableModel) table_info.getModel();
        modelTable.setRowCount(0);
        qlySinhVien.hienThiList();
        table_info.clearSelection();
        try {
            //SinhVien sinhVien = new SinhVien(txt_maSV.getText(),txt_hoTen.getText(),txt_Lop.getText());
            String[] array = new String[]{};
            for (SinhVien sv : qlySinhVien.list) {
                array = new String[]{sv.getMaSV(), sv.getHoTen(), sv.getGioiTinh(), sv.getNgaySinh(), sv.getNoiSinh(), sv.getDiaChi(), sv.getQuan(), sv.getMaKhoa(), String.valueOf(sv.getHocBong())};
                modelTable.addRow(array);
            }
        } catch (Exception ex) {

        }
    }//GEN-LAST:event_btnHienThiActionPerformed

    private void btnTimSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimSVActionPerformed

        DefaultTableModel modelTable = (DefaultTableModel) table_info.getModel();
        try {
            if (qlySinhVien.timKiem(txtMaSV.getText()) == true) {
                for (SinhVien sinhVien : qlySinhVien.list) {
                    String[] array = new String[]{sinhVien.getMaSV(), sinhVien.getHoTen(), sinhVien.getGioiTinh(), sinhVien.getNgaySinh(), sinhVien.getNoiSinh(),
                        sinhVien.getDiaChi(), sinhVien.getQuan(), sinhVien.getMaKhoa(), String.valueOf(sinhVien.getHocBong())};
                    modelTable.addRow(array);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Không tìm thấy sinh viên");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex);
        }

    }//GEN-LAST:event_btnTimSVActionPerformed

    private void btn_thoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_thoatActionPerformed
        // TODO add your handling code here:
        int j = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn thoát?", "Thoát", JOptionPane.YES_NO_OPTION);
        if (j == JOptionPane.YES_OPTION) {
            JF_Admin jfad = new JF_Admin();
            jfad.show();
            this.dispose();
        }
    }//GEN-LAST:event_btn_thoatActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        qlyKhoa.hienThiList();
        for (Khoa kh : qlyKhoa.list) {
            cboTenKhoa.addItem(kh.getTenKhoa());
        }
        hienThi();
    }//GEN-LAST:event_formWindowOpened

    private void btnSapXepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSapXepActionPerformed
        // TODO add your handling code here:
        qlySinhVien.sapXep();
        hienThi();
    }//GEN-LAST:event_btnSapXepActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing

    }//GEN-LAST:event_formWindowClosing

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JF_QuanLySinhvien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JF_QuanLySinhvien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JF_QuanLySinhvien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JF_QuanLySinhvien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JF_Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHienThi;
    private javax.swing.JButton btnSapXep;
    private javax.swing.JButton btnTimSV;
    private javax.swing.JButton btn_sua;
    private javax.swing.JButton btn_them;
    private javax.swing.JButton btn_thoat;
    private javax.swing.JButton btn_xoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cboTenKhoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel labelQuan;
    private com.toedter.calendar.JDateChooser ngaySinh;
    private javax.swing.JRadioButton rbtnNam;
    private javax.swing.JRadioButton rbtnNu;
    private javax.swing.JTable table_info;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtHocBong;
    private javax.swing.JTextField txtMaSV;
    private javax.swing.JTextField txtNoiSinh;
    private javax.swing.JTextField txtQuan;
    // End of variables declaration//GEN-END:variables
}
