/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qlysinhvien;

import qlysinhvien.KetQua;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import qlysinhvien.QuanLyTaiKhoan;

/**
 *
 * @author Administrator
 */
public class JF_XemDiemSV extends javax.swing.JFrame {

    //QLyTaiKhoan listTK = new QLyTaiKhoan();
    QLyKetQua listKQ = new QLyKetQua();
    QLySinhVien listSv = new QLySinhVien();
    private static String masv;

    /**
     * Creates new form JF_XemDiemSV
     */
    //private String maSV;
    public JF_XemDiemSV() {
        initComponents();
    }

    public JF_XemDiemSV(String maSV) {
        masv = maSV;
        initComponents();
    }

    /*   public JF_XemDiemSV(String maSV) {
        initComponents();
        this.maSV = maSV;
    }*/
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table_info = new javax.swing.JTable();
        btnThoat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        table_info.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã môn học", "Điểm"
            }
        ));
        jScrollPane1.setViewportView(table_info);

        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnThoat)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnThoat)
                .addContainerGap(121, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void hienThiSV(String maSV) {
        DefaultTableModel modelTable = (DefaultTableModel) table_info.getModel();
        modelTable.setRowCount(0);
        //listSv.hienThiList();
        listKQ.hienThiList();
        try {
            //SinhVien sv1 = new SinhVien(txt_maSV.getText(),txt_hoTen.getText(),txt_Lop.getText());
            String[] array = new String[]{};
            for (KetQua kq : listKQ.list) {
                if(kq.getMaSV().equals(maSV)){
                      array = new String[]{kq.getMaMonHoc(),String.valueOf(kq.getDiem())};
                modelTable.addRow(array);
                }
            }
        } catch (Exception ex) {

        }

    }
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
//        // TODO add your handling code here:
        //        DefaultTableModel modelTable = (DefaultTableModel) table_info.getModel();
        //        listTK.docFileTaiKhoan("TKSinhVien.txt");
        //        for (TaiKhoanSV tk : listTK.list) {
        //            if (tk.isTrangThai() == true) {
        //                String[] array = new String[]{};
        //                listKQ.docFile(tk.getTaiKhoan()+".txt");
        //                for (KetQua kq : listKQ.list) {
        //                    if (kq.getMaSV().equals(tk.getTaiKhoan())) {
        //                        array = new String[]{ kq.getMaMonHoc(), String.valueOf(kq.getDiem())};
        //                        modelTable.addRow(array);
        //                    }
        //                }
        //            }
        //        }
        hienThiSV(masv);
    }//GEN-LAST:event_formWindowOpened

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
        int j = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn thoát?", "Thoát", JOptionPane.YES_NO_OPTION);
        if (j == JOptionPane.YES_OPTION) {
            JF_SinhVien jf = new JF_SinhVien();
            jf.setVisible(true);
            this.dispose();
        } else {

        }
    }//GEN-LAST:event_btnThoatActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        int j = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn thoát?", "Thoát", JOptionPane.YES_NO_OPTION);
        if (j == JOptionPane.YES_OPTION) {

            System.exit(0);
        } else {

        }
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JF_XemDiemSV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JF_XemDiemSV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JF_XemDiemSV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JF_XemDiemSV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JF_Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThoat;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_info;
    // End of variables declaration//GEN-END:variables
}
